export const SCENES = [
  {
    age: 18,
    tag: '1 · EDUCATION',
    season: 'SUMMER',
    clip: 'new-intro',
    grade: 0,
    span: 4,
    title: 'University or work?',
    prompt: '“What are you thinkin’, love?” · Mum',
    A: {
      label: 'University',
      clip: 'br-uni',
      delta: 52000,
      why: 'Three years of tuition and living, all borrowed before you earn a penny. Interest starts on day one.',
      fact: 'Tuition rose from £3,290 in 2010 to £9,250 a year. England’s student-loan balance hit £266bn in 2024, up 12.9% in a year.',
      src: 'House of Commons Library',
      bill: {
        loan: true,
        footLabel: 'Borrowed to study',
        rows: [
          ['Tuition fees · 3 years', 27750],
          ['Rent while studying', 14250],
          ['Food + living', 6000],
          ['Interest (RPI)', 4000],
        ],
      },
    },
    B: {
      label: 'Start working',
      clip: 'br-work',
      delta: -33888,
      why: 'You live at home and pay your parents board. Most of your wage is left over.',
      fact: 'At 18 you can legally be paid £10.85/hour, £2.60 below the £13.45 real Living Wage.',
      src: 'Living Wage Foundation',
      bill: {
        inc: 1600,
        footLabel: 'Over 4 years',
        rows: [
          ['Board to parents', 418],
          ['Bus pass', 126],
          ['Phone + broadband', 68],
          ['Nights out + everyday', 282],
        ],
      },
    },
  },

  {
    age: 22,
    tag: '2 · HOUSING',
    season: 'AUTUMN',
    clip: 'scene-2',
    grade: 0.2,
    span: 3,
    title: 'Move to London or stay home?',
    prompt: '“This is where it all happens.” · your brother',
    A: {
      label: 'Move to London',
      clip: 'br-london',
      delta: 360,
      why: 'London costs a little more than you earn. You fall slightly behind every month.',
      fact: 'The average renter in England spends 36.3% of income on rent. In London, 41.6%.',
      src: 'ONS · Rental affordability',
      bill: {
        inc: 2050,
        footLabel: 'Over 3 years',
        rows: [
          ['Rent · London', 1236],
          ['Groceries', 330],
          ['Eating out', 41],
          ['Travel · zones 1-3', 185],
          ['Council tax', 113],
          ['Utilities', 52],
          ['Phone + streaming', 103],
        ],
      },
    },
    B: {
      label: 'Stay home and save',
      clip: 'br-home',
      delta: -20232,
      why: 'Still at home, you save a good chunk each month.',
      fact: 'The average first-time buyer is now 34, up from 29 in the mid-1990s. Saving faster than prices rise is the hard part.',
      src: 'English Housing Survey',
      bill: {
        inc: 1900,
        footLabel: 'Over 3 years',
        rows: [
          ['Board to parents · incl. food', 412],
          ['Moped finance · 3 years', 90],
          ['Moped insurance + tax', 57],
          ['Petrol', 52],
          ['Moped repairs + MOT', 26],
          ['Phone + streaming', 82],
          ['Council tax share', 93],
          ['Gym + clothes', 155],
          ['Nights out + everyday', 371],
        ],
      },
    },
  },

  {
    age: 25,
    tag: '3 · WORK',
    season: 'WINTER',
    clip: 'scene-3',
    grade: 0.45,
    span: 5,
    title: 'A steady job or your own thing?',
    prompt: '“Be your own boss.” / “Keep your head down, son.”',
    A: {
      label: 'Join a company',
      clip: 'br-company',
      delta: -6960,
      why: 'A steady wage, but a loan to repay and prices that keep rising. Only a little is left each month.',
      fact: 'British workers are living through a two-decade pay stagnation. Wages are roughly £15,000 a year lower than if pre-2008 growth had continued.',
      src: 'Resolution Foundation',
      bill: {
        inc: 2300,
        footLabel: 'Over 5 years',
        rows: [
          ['Rent', 956],
          ['Groceries', 340],
          ['Eating out', 42],
          ['Moped insurance + tax', 58],
          ['Petrol', 53],
          ['Moped repairs + MOT', 42],
          ['Council tax', 159],
          ['Gas + electric + water', 138],
          ['Phone + broadband', 64],
          ['Personal loan repayment', 300],
          ['Gym', 32],
        ],
      },
    },
    B: {
      label: 'Start a business',
      clip: 'br-business',
      delta: 28260,
      why: 'Startup costs land on a business loan while the income is still thin.',
      fact: 'Only 38% of new UK businesses are still trading five years on. More than 6 in 10 shut within five years.',
      src: 'ONS · Business Demography',
      bill: {
        inc: 1500,
        footLabel: 'Over 5 years',
        rows: [
          ['Rent', 743],
          ['Business loan repayment', 450],
          ['Groceries', 276],
          ['Eating out', 64],
          ['Council tax', 127],
          ['Utilities', 99],
          ['Everyday', 212],
        ],
      },
    },
  },

  {
    age: 30,
    tag: '4 · MONEY',
    season: 'WINTER NIGHT',
    clip: 'scene-4',
    grade: 0.68,
    span: 5,
    title: 'Invest it or keep it safe?',
    prompt: '“It’s growing.” / “In cash it’s safe.”',
    A: {
      label: 'Invest',
      clip: 'br-invest',
      delta: -19884,
      why: 'You save £458 a month, but one bad year in the market takes £7,596 of it.',
      fact: '38% of ISA holders earning over £150k max out their allowance, versus 6% of those earning £20k to £29k.',
      src: 'HMRC / Resolution Foundation',
      bill: {
        inc: 2600,
        footLabel: 'Over 5 years',
        rows: [
          ['Rent', 1062],
          ['Groceries', 361],
          ['Eating out', 42],
          ['Moped insurance + tax', 58],
          ['Petrol', 53],
          ['Moped repairs + MOT', 42],
          ['Council tax', 191],
          ['Utilities', 149],
          ['Phone + broadband', 64],
          ['Platform fees', 120],
          ['A bad year in the market', 7596, 'total'],
        ],
      },
    },
    B: {
      label: 'Save in cash',
      clip: 'br-cash',
      delta: -34680,
      why: 'Cash feels safe, but prices can climb faster than savings pay.',
      fact: 'UK inflation hit 11.1% in October 2022, a 41-year high, while most savings accounts paid far less.',
      src: 'ONS · Inflation',
      bill: {
        inc: 2600,
        footLabel: 'Over 5 years',
        rows: [
          ['Rent', 1062],
          ['Groceries', 361],
          ['Eating out', 42],
          ['Moped insurance + tax', 58],
          ['Petrol', 53],
          ['Moped repairs + MOT', 42],
          ['Council tax', 191],
          ['Utilities', 149],
          ['Phone + broadband', 64],
        ],
      },
    },
  },

  {
    age: 35,
    tag: '5 · FAMILY',
    season: 'DEEP WINTER',
    clip: 'scene-5',
    grade: 0.85,
    span: 10,
    title: 'Have kids or wait?',
    prompt: '“We’re running out of time.” · your partner',
    A: {
      label: 'Have kids',
      clip: 'br-kids',
      delta: 199120,
      why: 'You buy a family home. At 45, most of the mortgage is still owed. Your partner keeps working, so nursery adds £24,800 over two years.',
      fact: 'A full-time nursery place for an under-two averages £239 a week in England, about £12,400 a year, rivalling rent for many families.',
      src: 'Coram Family & Childcare',
      bill: {
        inc: 2900,
        footLabel: 'Over 10 years',
        rows: [
          ['Mortgage · family home', 1100],
          ['Groceries · family of three', 481],
          ['Eating out', 69],
          ['Commute', 252],
          ['Council tax', 218],
          ['Utilities', 241],
          ['Everyday', 575],
          ['Nursery · ages 1–3', 24800, 'total'],
          ['Family home · mortgage still owed at 45', 170000, 'owed'],
        ],
      },
    },
    B: {
      label: 'Wait',
      clip: 'br-nokids',
      delta: 27480,
      why: 'Waiting is not free either. You keep renting, and fertility care and follow-up costs add up.',
      fact: 'The fertility rate fell to 1.41 in 2024, the lowest since comparable records began in 1938.',
      src: 'ONS · Births',
      bill: {
        inc: 2900,
        footLabel: 'Over 10 years',
        rows: [
          ['Rent', 1261],
          ['Groceries', 413],
          ['Eating out', 69],
          ['Commute', 252],
          ['Council tax', 218],
          ['Utilities', 241],
          ['Everyday', 575],
          ['Private IVF · 2 rounds', 12000, 'total'],
        ],
      },
    },
  },

  {
    age: 45,
    tag: '6 · THE CYCLE',
    season: 'GREY MORNING',
    clip: 'scene-6',
    grade: 1,
    ending: true,
  },
]

export const SRC_URLS = {
  'House of Commons Library':
    'https://commonslibrary.parliament.uk/research-briefings/sn01079/',
  'Living Wage Foundation':
    'https://www.livingwage.org.uk/what-real-living-wage',
  'ONS · Rental affordability':
    'https://www.ons.gov.uk/peoplepopulationandcommunity/housing/bulletins/privaterentalaffordabilityengland/2024',
  'English Housing Survey':
    'https://www.ethnicity-facts-figures.service.gov.uk/housing/owning-and-renting/age-of-first-time-buyers/latest/',
  'Resolution Foundation':
    'https://www.resolutionfoundation.org/press-releases/british-workers-are-living-through-a-two-decade-wage-stagnation-costing-15000/',
  'ONS · Business Demography':
    'https://www.ons.gov.uk/businessindustryandtrade/business/activitysizeandlocation/bulletins/businessdemography/2024',
  'HMRC / Resolution Foundation':
    'https://www.resolutionfoundation.org/publications/ineffective-savings-accounts/',
  HMRC: 'https://www.gov.uk/government/collections/individual-savings-accounts-isa-statistics',
  'ONS · Inflation':
    'https://www.ons.gov.uk/economy/inflationandpriceindices/bulletins/consumerpriceinflation/october2022',
  'Coram Family & Childcare':
    'https://www.coramfamilyandchildcare.org.uk/research/childcare-survey-2025/',
  'ONS · Births':
    'https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/bulletins/birthsummarytablesenglandandwales/2024',
}

export const ENDING_FACT = {
  text: 'Millennials are the first modern generation not to be better off than their parents. Those born in the early 1980s earned less at 30, and just 27% owned a home by 30, down from 53%.',
  src: 'Resolution Foundation',
  url: 'https://www.resolutionfoundation.org/comment/flat-pay-little-wealth-and-a-shrinking-safety-net-whatever-happened-to-the-millennials/',
}

export const CHOICE_TIME = 9
