/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'builder-hub-settings': BuilderHubSetting;
    'builder-listing-settings': BuilderListingSetting;
    'site-settings-content': SiteSettingsContent;
    'site-navigation-content': SiteNavigationContent;
    'site-footer-content': SiteFooterContent;
    rfps: Rfp;
    ideas: Idea;
    'builder-resources': BuilderResource;
    circles: Circle;
    'circle-events': CircleEvent;
    'circle-initiatives': CircleInitiative;
    'circle-resources': CircleResource;
    'content-change-requests': ContentChangeRequest;
    'payload-kv': PayloadKv;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'builder-hub-settings': BuilderHubSettingsSelect<false> | BuilderHubSettingsSelect<true>;
    'builder-listing-settings': BuilderListingSettingsSelect<false> | BuilderListingSettingsSelect<true>;
    'site-settings-content': SiteSettingsContentSelect<false> | SiteSettingsContentSelect<true>;
    'site-navigation-content': SiteNavigationContentSelect<false> | SiteNavigationContentSelect<true>;
    'site-footer-content': SiteFooterContentSelect<false> | SiteFooterContentSelect<true>;
    rfps: RfpsSelect<false> | RfpsSelect<true>;
    ideas: IdeasSelect<false> | IdeasSelect<true>;
    'builder-resources': BuilderResourcesSelect<false> | BuilderResourcesSelect<true>;
    circles: CirclesSelect<false> | CirclesSelect<true>;
    'circle-events': CircleEventsSelect<false> | CircleEventsSelect<true>;
    'circle-initiatives': CircleInitiativesSelect<false> | CircleInitiativesSelect<true>;
    'circle-resources': CircleResourcesSelect<false> | CircleResourcesSelect<true>;
    'content-change-requests': ContentChangeRequestsSelect<false> | ContentChangeRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Uploaded media stored inside apps/web/public/cms/uploads so content JSON can reference repo-owned public assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Use an empty string only for decorative images. Content images need descriptive alt text.
   */
  alt: string;
  /**
   * Public path to copy into imageSrc fields, e.g. /cms/uploads/example.webp.
   */
  publicPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Repo-backed page metadata and sections. Saving validates and writes content/pages/en/<slug>.json through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Route-derived file slug, e.g. "/" -> "home".
   */
  slug: string;
  title: string;
  /**
   * Internal route starting with "/". Must match page.route in the JSON payload.
   */
  route: string;
  /**
   * Must match @repo/content pageCopySchema exactly.
   */
  page:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Raw Builders Hub page settings. Saving validates and writes content/builders-hub/settings/en.json through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-hub-settings".
 */
export interface BuilderHubSetting {
  id: number;
  /**
   * Use "builders-hub".
   */
  slug: string;
  /**
   * Must match @repo/content builderHubSettingsSchema exactly.
   */
  settings:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Settings for /builders-hub/ideas and /builders-hub/rfps listing pages. Saving writes the matching content/builders-hub/listings file through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-listing-settings".
 */
export interface BuilderListingSetting {
  id: number;
  page: 'ideas' | 'rfps';
  title: string;
  description: string;
  breadcrumbLabel: string;
  submitCtaLabel: string;
  submitCtaHref: string;
  submitCtaExternal?: boolean | null;
  defaultView: 'grid' | 'list';
  pageSize: number;
  previousLabel: string;
  nextLabel: string;
  bottomCtaTitle: string;
  bottomCtaLabel: string;
  bottomCtaHref: string;
  bottomCtaExternal?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Repo-backed site settings. Saving validates and writes content/site/en/settings.json through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings-content".
 */
export interface SiteSettingsContent {
  id: number;
  /**
   * Use "settings".
   */
  slug: string;
  /**
   * Must match @repo/content siteSettingsSchema.
   */
  settings:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Repo-backed site navigation. Saving validates and writes content/site/en/navigation.json through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation-content".
 */
export interface SiteNavigationContent {
  id: number;
  /**
   * Use "navigation".
   */
  slug: string;
  /**
   * Must match @repo/content navigationSchema.
   */
  navigation:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Repo-backed site footer. Saving validates and writes content/site/en/footer.json through a GitHub pull request.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer-content".
 */
export interface SiteFooterContent {
  id: number;
  /**
   * Use "footer".
   */
  slug: string;
  /**
   * Must match @repo/content footerSchema.
   */
  footer:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Funded calls for builders to ship Logos-powered applications. Saving creates a GitHub pull request for review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfps".
 */
export interface Rfp {
  id: number;
  /**
   * URL-safe identifier — kebab-case, ASCII only. Used as the directory name in `content/builders-hub/rfps/<slug>/`.
   */
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  /**
   * One-line pitch (~80 chars) shown on the home grid card and listing rows.
   */
  tagline?: string | null;
  summary: string;
  /**
   * Full-length RFP description — 2–3 paragraphs of context and deliverables.
   */
  description: string;
  /**
   * Per-card CTA text. Defaults to "Apply" when empty.
   */
  ctaLabel?: string | null;
  rewardAmount: number;
  rewardCurrency: 'USDC';
  /**
   * Optional XP bonus.
   */
  rewardXp?: number | null;
  /**
   * Where the "Apply" CTA points. Internal route ("/path") or external https URL.
   */
  applyUrl: string;
  /**
   * Free-form lower-case tags — used for filtering on the listing page.
   */
  tags?: string[] | null;
  featured?: boolean | null;
  /**
   * Sort key (ascending). Lower numbers appear first on the home grid.
   */
  order?: number | null;
  publishedAt?: string | null;
  closesAt?: string | null;
  /**
   * Display name (e.g. "Logos Core").
   */
  ownerName?: string | null;
  /**
   * Stored without the leading "@".
   */
  ownerHandle?: string | null;
  /**
   * Slugs from the Ideas collection that this RFP relates to.
   */
  relatedIdeas?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community-submitted concepts driving sovereignty forward. Saving creates a GitHub pull request for review.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideas".
 */
export interface Idea {
  id: number;
  /**
   * URL-safe identifier — kebab-case, ASCII only. Used as the directory name in `content/builders-hub/ideas/<slug>/`.
   */
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  /**
   * One-line pitch (~80 chars) shown on the home Ideas table and listing rows.
   */
  tagline?: string | null;
  summary: string;
  description: string;
  /**
   * Per-row CTA text. Defaults to "Discuss" when empty.
   */
  ctaLabel?: string | null;
  /**
   * Display name (optional).
   */
  submitterName?: string | null;
  /**
   * Stored without the leading "@". Validation rejects "@" prefixes.
   */
  submitterHandle: string;
  /**
   * Leave empty if no reward.
   */
  rewardAmount?: number | null;
  rewardCurrency?: 'USDC' | null;
  rewardXp?: number | null;
  /**
   * Forum thread for the idea (optional). External https URL.
   */
  discussionUrl?: string | null;
  tags?: string[] | null;
  featured?: boolean | null;
  /**
   * Sort key (ascending).
   */
  order?: number | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resources shown on Builders Hub. Shape mirrors content/builders-hub/resources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-resources".
 */
export interface BuilderResource {
  id: number;
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  description: string;
  ctaLabel: string;
  href: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Local Logos chapters. Shape mirrors content/circles/circles fixtures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles".
 */
export interface Circle {
  id: number;
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  name: string;
  description: string;
  city: string;
  country: string;
  region?: string | null;
  lat: number;
  lng: number;
  timezone: string;
  memberCount?: number | null;
  discordChannel?: string | null;
  discordUrl?: string | null;
  forumUrl?: string | null;
  joinUrl: string;
  organizers?:
    | {
        name: string;
        handle?: string | null;
        id?: string | null;
      }[]
    | null;
  imageSrc?: string | null;
  imageAlt?: string | null;
  imageWidth?: number | null;
  imageHeight?: number | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Circle gatherings. Shape mirrors content/circles/events fixtures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-events".
 */
export interface CircleEvent {
  id: number;
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  circleSlug: string;
  title: string;
  locationLabel: string;
  startsAt: string;
  endsAt?: string | null;
  timezone: string;
  venueName?: string | null;
  address?: string | null;
  eventUrl?: string | null;
  hostedBy?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sequenceNumber?: number | null;
  imageSrc?: string | null;
  imageAlt?: string | null;
  imageWidth?: number | null;
  imageHeight?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Winnable local issues. Shape mirrors content/circles/initiatives fixtures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-initiatives".
 */
export interface CircleInitiative {
  id: number;
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  circleSlug: string;
  href: string;
  locationLabel: string;
  title: string;
  description: string;
  ctaLabel: string;
  imageSrc?: string | null;
  imageAlt?: string | null;
  imageWidth?: number | null;
  imageHeight?: number | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resources shown on the Circles page. Shape mirrors content/circles/resources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-resources".
 */
export interface CircleResource {
  id: number;
  slug: string;
  status: 'draft' | 'review' | 'published' | 'archived';
  title: string;
  description: string;
  ctaLabel: string;
  href: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mirror of in-flight content PRs. Rows are created by the CMS workflow service — do not edit by hand unless you know what you are doing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-change-requests".
 */
export interface ContentChangeRequest {
  id: number;
  /**
   * Logical content type — e.g. "pages", "rfp", "circle-event". Matches the loader namespace.
   */
  contentType: string;
  /**
   * Repo-relative path the PR touches (e.g. "content/pages/en/home.json"). Indexed for lock queries.
   */
  targetPath: string;
  /**
   * GitHub branch name. One row per branch.
   */
  branchName: string;
  /**
   * GitHub PR number once opened.
   */
  pullRequestNumber?: number | null;
  /**
   * Public GitHub PR URL once opened.
   */
  pullRequestUrl?: string | null;
  status: 'draft' | 'open' | 'merged' | 'closed';
  /**
   * Latest commit SHA on the branch — useful for cache invalidation.
   */
  commitSha?: string | null;
  /**
   * Payload user who triggered this change request.
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  publicPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  route?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-hub-settings_select".
 */
export interface BuilderHubSettingsSelect<T extends boolean = true> {
  slug?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-listing-settings_select".
 */
export interface BuilderListingSettingsSelect<T extends boolean = true> {
  page?: T;
  title?: T;
  description?: T;
  breadcrumbLabel?: T;
  submitCtaLabel?: T;
  submitCtaHref?: T;
  submitCtaExternal?: T;
  defaultView?: T;
  pageSize?: T;
  previousLabel?: T;
  nextLabel?: T;
  bottomCtaTitle?: T;
  bottomCtaLabel?: T;
  bottomCtaHref?: T;
  bottomCtaExternal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings-content_select".
 */
export interface SiteSettingsContentSelect<T extends boolean = true> {
  slug?: T;
  settings?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation-content_select".
 */
export interface SiteNavigationContentSelect<T extends boolean = true> {
  slug?: T;
  navigation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer-content_select".
 */
export interface SiteFooterContentSelect<T extends boolean = true> {
  slug?: T;
  footer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfps_select".
 */
export interface RfpsSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  title?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  ctaLabel?: T;
  rewardAmount?: T;
  rewardCurrency?: T;
  rewardXp?: T;
  applyUrl?: T;
  tags?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  closesAt?: T;
  ownerName?: T;
  ownerHandle?: T;
  relatedIdeas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideas_select".
 */
export interface IdeasSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  title?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  ctaLabel?: T;
  submitterName?: T;
  submitterHandle?: T;
  rewardAmount?: T;
  rewardCurrency?: T;
  rewardXp?: T;
  discussionUrl?: T;
  tags?: T;
  featured?: T;
  order?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "builder-resources_select".
 */
export interface BuilderResourcesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles_select".
 */
export interface CirclesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  name?: T;
  description?: T;
  city?: T;
  country?: T;
  region?: T;
  lat?: T;
  lng?: T;
  timezone?: T;
  memberCount?: T;
  discordChannel?: T;
  discordUrl?: T;
  forumUrl?: T;
  joinUrl?: T;
  organizers?:
    | T
    | {
        name?: T;
        handle?: T;
        id?: T;
      };
  imageSrc?: T;
  imageAlt?: T;
  imageWidth?: T;
  imageHeight?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-events_select".
 */
export interface CircleEventsSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  circleSlug?: T;
  title?: T;
  locationLabel?: T;
  startsAt?: T;
  endsAt?: T;
  timezone?: T;
  venueName?: T;
  address?: T;
  eventUrl?: T;
  hostedBy?:
    | T
    | {
        name?: T;
        id?: T;
      };
  featured?: T;
  sequenceNumber?: T;
  imageSrc?: T;
  imageAlt?: T;
  imageWidth?: T;
  imageHeight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-initiatives_select".
 */
export interface CircleInitiativesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  circleSlug?: T;
  href?: T;
  locationLabel?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  imageSrc?: T;
  imageAlt?: T;
  imageWidth?: T;
  imageHeight?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-resources_select".
 */
export interface CircleResourcesSelect<T extends boolean = true> {
  slug?: T;
  status?: T;
  title?: T;
  description?: T;
  ctaLabel?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-change-requests_select".
 */
export interface ContentChangeRequestsSelect<T extends boolean = true> {
  contentType?: T;
  targetPath?: T;
  branchName?: T;
  pullRequestNumber?: T;
  pullRequestUrl?: T;
  status?: T;
  commitSha?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
